(function(){
var KasperskyLab = (function (ns) { ns.ContentSecurityPolicyNonceAttribute = '7CF8E5626E964F90AE6082D690A6C9C7'; return ns;}) (KasperskyLab || {});
var KasperskyLab=function(g){function k(a){return"undefined"===typeof a?"undefined":null===a?"null":Object.prototype.toString.call(a).match(/^\[object\s(.*)\]$/)[1]}function e(a){if(null===a||Infinity==a||-Infinity==a||a===h)return"null";var d=k(a);if("Boolean"==d)return""+a;if("Number"==d)return window.isNaN(a)?"null":""+a;if("String"==d)return'"'+a+'"';if("object"==typeof a){e.check||(e.check=[]);for(var c=0,b=e.check.length;c<b;++c)if(e.check[c]===a)throw new TypeError;e.check.push(a);c="";if("Array"==
d){for(var d=0,f=a.length;d<f;++d)c+=e(a[d])+",";e.check.pop();return"["+c.slice(0,-1)+"]"}for(f in a)a.hasOwnProperty(f)&&(c+='"'+f+'":'+e(a[f])+",");e.check.pop();return"{"+c.slice(0,-1)+"}"}return h}var h,l={source:null,b:/^[\x20\t\n\r]*(?:([,:\[\]{}]|true|false|null)|(-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)|"((?:[^\r\n\t\\\"]|\\(?:["\\\/trnfb]|u[0-9a-fA-F]{4}))*)")/,a:function(){throw new SyntaxError("JSON syntax error");},c:function(a){this.source=a.input.slice(a[0].length);return this.b.exec(this.source)},
f:function(){for(var a=this.b.exec(this.source),d=a&&"]"!=a[1],c=[];;a=this.c(a)){a||this.a();if(d)c.push(this.d(a)),a=this.b.exec(this.source);else if(a[1])if("]"==a[1])break;else","!=a[1]&&this.a();else this.a();d=!d}return c},g:function(){for(var a,d=!0,c={},b=this.b.exec(this.source);;b=this.c(b))if(b||this.a(),d){if(b[1]&&"}"==b[1])break;else(b[1]||b[2]||!b[3])&&this.a();a=b[3];(b=this.c(b))&&b[1]&&":"==b[1]||this.a();d=!1}else{a||this.a();c[a]=this.d(b);b=this.c(this.b.exec(this.source));if(b[1])if("}"==
b[1])break;else","!=b[1]&&this.a();else this.a();a=h;d=!0}return c},d:function(a){if(a[1])switch(a[1]){case "[":return this.source=this.source.slice(a[0].length),this.f();case "{":return this.source=this.source.slice(a[0].length),this.g();case "true":return!0;case "false":return!1;case "null":return null;default:this.a()}else if(a[2])return+a[2];return a[3].replace(/\\(?:u(.{4})|(["\\\/\']))/g,function(a,c,b){return c?String.fromCharCode(parseInt(c,16)):b})},e:function(a){if("String"!=k(a))throw new TypeError;
this.source=a;(a=this.b.exec(this.source))||this.a();return this.d(a)}};g.JSONStringify=function(a){return e(a)};g.JSONParse=function(a){return l.e(a)};return g}.call(this,KasperskyLab||{});
var KasperskyLab=function(a){a.MaxRequestDelay=2E3;a.Log=function(d){};a.GetResourceSrc=function(d){return"/7C9C6A096D2806EA09F469E6265E8FC7"+d};a.AddEventListener=function(d,a,c){"addEventListener"in d?d.addEventListener(a,function(d){c(d||window.event)},!1):d.attachEvent("on"+a,function(a){c.call(d,a||window.event)})};a.AddRemovableEventListener=function(d,a,c){d.addEventListener?d.addEventListener(a,c,!1):d.attachEvent("on"+a,c)};a.RemoveEventListener=function(a,f,c){a.removeEventListener?a.removeEventListener(f,
c,!1):a.detachEvent("on"+f,c)};a.AddStyles=function(a){if("object"==typeof a&&a.constructor==Array){var f=document.createElement("style");f.type="text/css";f.setAttribute("nonce",KasperskyLab.ContentSecurityPolicyNonceAttribute);for(var c=0,k=a.length;c<k;++c){var h=f,m=a[c];h.styleSheet?h.styleSheet.cssText+=m+"\n":h.appendChild(document.createTextNode(m))}document.head?document.head.appendChild(f):document.getElementsByTagName("head")[0].appendChild(f)}};a.GetCurrentTime=function(){return(new Date).getTime()};
a.GetPageScroll=function(){return{left:document.documentElement&&document.documentElement.scrollLeft||document.body.scrollLeft,top:document.documentElement&&document.documentElement.scrollTop||document.body.scrollTop}};a.GetPageHeight=function(){return document.documentElement.clientHeight||document.body.clientHeight};a.GetPageWidth=function(){return document.documentElement.clientWidth||document.body.clientWidth};return a}(KasperskyLab||{}),KasperskyLab=function(a){a.Balloon=function(d,f,c,k){function h(){l&&
clearTimeout(l);l=0}function m(){h.call(p)}function s(b){l||(h(),l=setTimeout(function(){n()},200))}function t(b){k&&k(b||window.event)&&n.call(p)}function u(){KasperskyLab.AddStyles([".kisb * { position: relative; display:block; overflow-x:hidden; width: auto; margin:0; padding:0; font-family: Verdana; line-height: 150%; text-indent:0; border:0; text-align:left; box-sizing:content-box; letter-spacing: normal;}",".kisb { z-index:2147483647; width: 280px; cursor:default; display:block;}",".kisb a { text-decoration: underline; display:inline-block; }",
".kisb a:hover { text-decoration: none; }",".kisb a, .kisb a:link, .kisb a:hover, .kisb a:visited { color: #008ccc;}"]);var b=document.createElement("div");b.className="kisb";b.id=q;a.AddEventListener(b,"mouseout",s);a.AddEventListener(b,"mouseover",m);a.AddEventListener(b,"click",t);c(b);b.style.visibility="hidden";document.body.appendChild(b);return b}function v(b){b=document.attachEvent&&document.documentMode&&5==document.documentMode?{width:b.clientWidth||b.scrollWidth,height:b.clientHeight||
b.scrollHeight}:b.getBoundingClientRect();return{width:b.width?b.width:b.right-b.left,height:b.height?b.height:b.bottom-b.top}}function n(){g&&(g.style.visibility="hidden")}function r(b,a,d){(g=document.getElementById(q))||(g=u());if("visible"!=g.style.visibility){var c=0,e=0,e=v(g);if(1==f)c=b,e=a-(e.height?e.height:20);else if(2==f){var c=KasperskyLab.GetPageWidth(),k=e.width/2,c=k>b?0:k+b>c?c-e.width:b-k;b=KasperskyLab.GetPageHeight();e=a+e.height>b?a-e.height:a}else c=b,e=a;0>e&&(e=0);a=KasperskyLab.GetPageScroll();
e+=a.top;c+=a.left;g.style.position="absolute";g.style.left=Math.round(c).toString()+"px";g.style.top=Math.round(e).toString()+"px";g.style.visibility="visible";h();l=setTimeout(function(){n()},d)}}var p=this,g=null,l=null,q="balloon_parent_div_"+d;this.ShowBalloon=function(a,c,d){h();c?l=setTimeout(function(){var c=a();c.isNeed?r(c.x,c.y,d):n()},c):(c=a(),r(c.x,c.y,d))}};return a}(KasperskyLab||{});
(function(){
var nssseaiesinontc=function(f){function r(l,k){try{f.Log(k),setTimeout(function(){var c=s.GetAsyncRequest();c?(c.open("POST",l+"/log"),c.send(k)):f.Log("Ajax is not supported. Cannot send log to product")},0)}catch(c){f.Log("Sending log error: "+(c.message||c))}}(function(f,k){for(var c=f.toLowerCase(),m=0,n=document.scripts.length;m<n;++m){var g=document.scripts[m];if("string"===typeof g.src&&76<g.src.length&&0<g.src.toLowerCase().indexOf(c)&&/\/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\/main.js/.test(g.src)){g.parentElement.removeChild(g);
break}}})("7CF8E5626E964F90AE6082D690A6C9C7");var s=function(){var f=window.XMLHttpRequest&&window.XMLHttpRequest.prototype.open,k=window.XMLHttpRequest&&window.XMLHttpRequest.prototype.send;return{GetAsyncRequest:function(){var c=window.XDomainRequest?new window.XDomainRequest:new window.XMLHttpRequest;window.XDomainRequest||(c.open=f,c.send=k);return c},GetSyncRequest:function(){var c=new window.XMLHttpRequest;c.open=f;c.send=k;return c}}}(),y=function(l){function k(){try{d&&clearTimeout(d)}catch(e){}try{a&&(a.onload=
function(){},a.onerror=function(){},a.abort())}catch(q){}a=d=null}function c(){for(var e in h)if(h.hasOwnProperty(e))return!1;return!0}function m(){var e=f.MaxRequestDelay,a=f.GetCurrentTime(),b;for(b in h)try{var c=h[b].onPing;if(c){var d=c(a);d<e&&1<d&&d<f.MaxRequestDelay&&(e=d)}}catch(g){var k=h[b].onError;k&&k("UpdateDelay: "+(g.message||g))}p=e}function n(e){for(var a in h){var b=h[a].onError;b&&b(e)}}function g(e){return e&&(e=e.split(".",2),2==e.length)?e[0]:null}function t(e){return(e=h[e])?
e.methods:null}function u(e,a){try{e.open("POST",a),e.onerror=function(){n("AJAX ping network error!")},e.onload=function(){var a=e.responseText&&f.JSONParse(e.responseText);if(!a||"undefined"===typeof a.parameters||"undefined"===typeof a.method)n("AJAX pong is not received. Product is deactivated");else if(a.method.length){f.Log("Try to find js callback "+a.method);var b=g(a.method);if(b)a:{var c=a.method,a=a.parameters,q=t(b);if(q&&(q=q[c]))try{q(a);r(l,c+" executed.");break a}catch(d){r(l,"Call "+
c+" in plugin "+b+" error: "+(d.message||d))}r(l,"Cannot call "+c+" for plugin "+b)}}},e.send(x)}catch(b){n("Ajax send ping exception: "+(b.message||b))}}var v=l+"/from",h={},p=f.MaxRequestDelay,d=null,a=null,x=f.JSONStringify({result:0,method:"ping",parameters:[]});this.RegisterMethod=function(a,c){var b=g(a);if(b)if(b=t(b)){if(b[a])throw"Already registered method "+a;b[a]=c}else throw"Cannot registered "+a;};this.RegisterPlugin=function(e,f,b){if(h[e])throw"Already started plugin "+e;var g={onError:null,
onPing:null,methods:{}};h[e]=g;g.onError=b;g.onPing=f;null==d&&(m(),c()||(d=setTimeout(function w(){try{m(),c()||(a=a||s.GetAsyncRequest(),u(a,v),d=setTimeout(w,p))}catch(b){n("Send ping request: "+(b.message||b))}},p)))};this.UnregisterPlugin=function(a){delete h[a];c()&&k()};this.UnregisterAll=function(){0!=h.length&&(k(),h={})};this.IsEmpty=c};return new function(l,k,c){function m(a,c,e,d){try{var b=s.GetAsyncRequest();b||d&&d("Cannot create AJAX request!");b.open("POST",p+"/to/"+a);var g=setTimeout(function(){b.abort();
d&&d("Cannot send AJAX request for calling "+a)},12E4);b.onerror=function(){b.onerror=function(){};b.onload=function(){};d&&d("AJAX request error for calling "+a)};b.onload=function(){clearTimeout(g);g=null;b.onload=function(){};b.onerror=function(){};if(b.responseText){if(e){var a=f.JSONParse(b.responseText);e(a.result,a.parameters)}b=null}else b=null,d&&d("AJAX request with unsupported url type!")};b.send(f.JSONStringify({result:0,method:a,parameters:c}));f.Log("Call native function "+a)}catch(h){d&&
d("AJAX request "+a+" exception: "+(h.message||h))}}function n(a,c,e,d){try{var b=s.GetSyncRequest();if(!b)return d&&d("Cannot create AJAX request!"),!1;b.open("POST",p+"/to/"+a,!1);f.Log("SyncCall native function "+a);b.send(f.JSONStringify({result:0,method:a,parameters:c}));if(200===b.status&&b.responseText){if(e){var g=f.JSONParse(b.responseText);e(g.result,g.parameters)}return!0}}catch(h){d&&d("AJAX request "+a+" exception: "+(h.message||h))}return!1}function g(){try{d.UnregisterAll(),f.Log("session stopped")}catch(a){}}
function t(a){f.Log("DeactivatePlugin "+a);d.UnregisterPlugin(a);d.IsEmpty()&&g()}function u(a,c,e){f.Log("ActivatePlugin "+a);d.IsEmpty();d.RegisterPlugin(a,c,function(c){e&&e(c);d.UnregisterPlugin(a);d.IsEmpty()&&g()})}function v(a,c){f.Log("RegisterMethod "+a);d.RegisterMethod(a,c)}var h=this,p=(c||"/")+l+"/"+k,d=new y(p);this.Log=function(a){r(p,a)};this.InitializePlugin=function(a){a(function(){u.apply(h,arguments)},function(){v.apply(h,arguments)},function(){m.apply(h,arguments)},function(){t.apply(h,
arguments)},function(){n.apply(h,arguments)})}}("548F9659-BC13-8E49-A302-E2683A183EA0","B562F5CC-C4BA-A74E-9EE2-364CD9111B94","/")}(KasperskyLab);
(function(b,l){var r=function(c,k){function r(){return b.MaxRequestDelay}function s(a){l.Log("ERR AB - "+(a.message||a))}function t(a){u.ShowBalloon(function(){return{isNeed:!0,x:v,y:w}},a,2E3)}function A(){u.ShowBalloon(function(){return{isNeed:!1}},500)}function d(a){var b={focus:!0,focusin:!0,pageshow:!0,blur:!1,focusout:!1,pagehide:!1};a=a||window.event;(b.hasOwnProperty(a.type)?b[a.type]:document[e])||A()}function B(a){f(!!a.ctrlKey);if(a=a.target||a.srcElement)n=a.src,h&&(p=!0,x&&t(500))}function C(){p=
!1}function D(a){v=a.clientX;w=a.clientY;f(!!a.ctrlKey)}function f(a){(x=a)?(b.RemoveEventListener(document,"keydown",q),b.AddRemovableEventListener(document,"keyup",y)):(b.RemoveEventListener(document,"keyup",y),b.AddRemovableEventListener(document,"keydown",q))}function q(a){(a||window.event).keyCode===k&&(f(!0),h&&p&&t(500));return!0}function y(){f(!1);return!0}function E(a){b.AddRemovableEventListener(a,"keydown",q);e in a?a.addEventListener("visibilitychange",d):(e="mozHidden")in a?a.addEventListener("mozvisibilitychange",
d):(e="webkitHidden")in a?a.addEventListener("webkitvisibilitychange",d):(e="msHidden")in a?a.addEventListener("msvisibilitychange",d):"onfocusin"in a?a.onfocusin=a.onfocusout=d:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=d;void 0!==a[e]&&d({type:a[e]?"blur":"focus"});a=a.getElementsByTagName("img");for(var m=0,f=a.length;m<f;++m){var g=a[m],c=g.attributes.getNamedItem("KasperskyLab_AntiBanner");if(null===c||"on"!==c.value)g.setAttribute("KasperskyLab_AntiBanner","on"),b.AddEventListener(g,
"mouseover",B),b.AddEventListener(g,"mouseout",C),b.AddEventListener(g,"mousemove",D)}}var n=0,v=0,w=0,p=!1,h="Enabled"===c,x=!1,e="hidden",z;l.InitializePlugin(function(a,b,c){z=c;a("ab",r,s);b("ab.setstate",function(a){h=a.length&&"Enabled"===a[0]})});var u=new b.Balloon("ab",1,function(a){b.AddStyles(['.kisb .kl_abmenu { font-size:12px; font-family: "Segoe UI", Arial, sans-serif; color: #FFFFFF; float: left; padding: 8px; border: 1px solid #FFFFFF; background: #057662; background: -moz-linear-gradient(#057662, #1a8171);background: -ms-linear-gradient(#057662, #1a8171);background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #057662), color-stop(100%, #1a8171)); background: -webkit-linear-gradient(#057662, #1a8171); background: -o-linear-gradient(#057662, #1a8171);filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#057662", endColorstr="#1a8171"); -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr="#057662", endColorstr="#1a8171")";background: linear-gradient(#057662, #1a8171);border-radius: 8px;}']);
var c=document.createElement("div");c.className="kl_abmenu";c.appendChild(document.createTextNode("Add to Anti-Banner"));a.appendChild(c)},function(a){f(!!a.ctrlKey);h&&n&&z("ab.sdkdAioTolcBLt",[n],null,s);return!0});window.document&&E(window.document)},k=null;b.AddEventListener(window,"load",function(){try{k||(k=new r("Enabled",17))}catch(b){l.Log("Antibanner exception: "+(b.message||b))}})})(KasperskyLab||{},nssseaiesinontc);

(function (ns) { ns.DefaultUrlAdvisorEnable = true; ns.DefaultUrlAdvisorState = 'Enabled'; ns.DefaultUrlAdvisorMode = 1; ns.DefaultUrlAdvisorTermsUrl = 'http://redirect.kaspersky.com?target=threatcatterms&act-local=en-GB&customization=&rpe=1'; ns.DefaultUrlAdvisorInfoUrl = 'http://redirect.kaspersky.com?target=threatcatinfo&act-local=en-GB&customization=&act-pcid={7CF8E562-6E96-4F90-AE60-82D690A6C9C7}&act-lic-type=6&act-lic-status=1&act-lic-lifespan=730&act-lic-daystillexpiration=352&act-pid=ksospc&act-pv=15.0.2.361&ppcs-id=0&act-ksn=1'; }) (KasperskyLab || {});
(function(c){c.UrlAdvisorBalloon=function(){function c(m){return KasperskyLab.GetResourceSrc("/ua/"+m)}function r(m){if(1E10<=m.low){var c=Math.floor(m.low/1E10);m.low%=1E10;m.high+=c}}function u(c){return v[c].name}function s(c,f,e){if(f)for(var n=0,h=f.length;n<h;++n){var k=document.createElement("span");k.className="kl_tag";k.appendChild(document.createTextNode(e(f[n])));c.appendChild(k)}}function x(c){for(;0<c.childNodes.length;)c.removeChild(c.childNodes[0])}function F(c){if(n){c=c||event;var f=
n.getBoundingClientRect();c.clientX>f.left&&c.clientX<f.right&&c.clientY>f.top&&c.clientY<f.bottom||!n||(n.style.visibility="hidden")}}var v=[{name:"Unknown",bit:-1},{name:"Phishing resource",bit:62},{name:"Dangerous resource",bit:63}],t=[{headerClass:"kl_header green",headerNode:"Safe web page",textNode:"Safe web resource (according to Kaspersky Lab reputation service)",marker:"kl_marker allow"},{headerClass:"kl_header grey",headerNode:"Unknown web page",textNode:"No information on web resource safety (according to Kaspersky Lab reputation service)",
marker:"kl_marker unknown"},{headerClass:"kl_header red",headerNode:"Dangerous web page",textNode:"Dangerous web resource (according to Kaspersky Lab reputation service)",marker:"kl_marker disallow"}],n=null;this.ShowBalloon=function(m,f,e,w,h){n=document.getElementById("balloon_parent_div");if(!n){KasperskyLab.AddStyles([".kisb * { position: relative; display:block; overflow-x:hidden; width: auto; margin:0; padding:0; font-family: Verdana; line-height: 150%; text-indent:0; border:0; box-sizing:content-box; color:#000000; letter-spacing: normal; text-align: left; direction: ltr;}",
".kisb { z-index:2147483647; width: 280px; cursor:default; display:block;}",".kisb .kl_header { padding:27px 26px 10px 26px;  }",".kisb .kl_header.red { background-image:url("+c("header_red.png")+");}",".kisb .kl_header.grey { background-image:url("+c("header_grey.png")+");}",".kisb .kl_header.green { background-image:url("+c("header_green.png")+");}",".kisb .kl_content { background: url("+c("content.png")+") repeat-y top left; padding:10px 26px 10px 26px;}",".kisb .kl_content .block { width: 228px!important; }",
".kisb .kl_marker { margin-top: 5px; margin-bottom:10px; padding-top:2px; padding-left:25px; background-position-x: 0; background-position-y: 0; background-repeat: no-repeat; word-wrap: break-word;}",".kisb .kl_marker.allow { background-image: url( "+c("allow.png")+")}",".kisb .kl_marker.disallow { background-image: url("+c("disallow.png")+")}",".kisb .kl_marker.unknown { background-image: url("+c("unknown.png")+")}",".kisb .kl_tag { display:inline-block; background: left top url("+c("tag.png")+") no-repeat; padding-left:12px; padding-right:5px; margin-right:5px; margin-bottom:5px; font-size: 7.5pt;}",
".kisb .kl_external { margin-top: 15px; padding-top:2px; padding-left:20px; background-position-x: left; background-position-y: top; background-repeat: no-repeat;}",".kisb .kl_external { background-image: url("+c("external.png")+")}",".kisb .kl_footer { background: url("+c("footer.png")+") no-repeat bottom left; padding:6px 26px 22px 26px;}",".kisb .kl_content * { font-size:8pt; }",".kisb a { text-decoration: underline; display:inline-block; }",".kisb a:hover { text-decoration: none; }",".kisb a, .kisb a:link, .kisb a:hover, .kisb a:visited { color: #008ccc;}",
".kisb .kl_header { font-size:12pt; color: #ffffff;  }",".kisb .kl_footer a { font-size:8pt; color: #4d4d4d; text-decoration:underline; }"]);var k=document.createElement("div");k.className="kisb";k.id="balloon_parent_div";k.onmouseout=F;var l=document.createElement("div");l.id="balloon_header";k.appendChild(l);l=document.createElement("div");l.className="kl_content";var b=document.createElement("div");b.className="block";l.appendChild(b);var d=document.createElement("div");d.className="block";d.id=
"balloon_content";b.appendChild(d);d=document.createElement("div");d.className="kl_marker allow";d.id="balloon_marker";b.appendChild(d);d=document.createElement("div");d.id="balloon_tags";b.appendChild(d);d=document.createElement("a");d.href="#";d.id="balloon_external";d.className="kl_external";d.target="_blank";d.appendChild(document.createTextNode("Additional information"));b.appendChild(d);k.appendChild(l);l=document.createElement("div");l.className="kl_footer";l.id="balloon_footer";
b=document.createElement("a");b.id="balloon_terms";b.target="_blank";b.appendChild(document.createTextNode("Terms of Use"));l.appendChild(b);k.appendChild(l);k.style.visibility="hidden";document.body.appendChild(k);n=k}var b=document.getElementById("balloon_header"),d=document.getElementById("balloon_content"),q=document.getElementById("balloon_marker"),g=document.getElementById("balloon_tags"),k=document.getElementById("balloon_external"),l=document.getElementById("balloon_terms");
x(b);x(d);x(q);x(g);b.className=t[e.rating-1].headerClass;b.appendChild(document.createTextNode(t[e.rating-1].headerNode));d.appendChild(document.createElement("b")).appendChild(document.createTextNode(t[e.rating-1].textNode));q.className=t[e.rating-1].marker;q.appendChild(document.createTextNode(e.url));if(e.categories&&0!=e.categories.length||e.threats&&0!=e.threats.length)g.appendChild(document.createElement("br")),g.appendChild(document.createElement("br")),g.appendChild(document.createTextNode("Categories: ")),
b=g.appendChild(document.createElement("div")),s(b,e.categories,KasperskyLab.ConvertCategory),s(b,e.threats,u);b=e.url.indexOf("?");b=-1!=b?b=e.url.substring(0,b):e.url;w=w+"&act-exturl="+b+"&act-threat-cat="+(e.rating-1)+"&act-content-cat=";var g=e.threats,p=e.categories;e={high:0,low:0};b=[];if(g)for(d=0,q=g.length;d<q;++d)b.push(v[g[d]].bit);if(p)for(d=0,q=p.length;d<q;++d)b.push(p[d]-1);d=0;for(q=b.length;d<q;++d)g=b[d],0>g||64<=g?g={high:0,low:0}:(p={high:0,low:Math.pow(2,Math.min(50,g))},r(p),
50<g&&(p.low*=Math.pow(2,g-50),p.high*=Math.pow(2,g-50),r(p)),g=p),e.high+=g.high,e.low+=g.low,r(e);b="";if(e.high)for(b+=e.high,d=e.low.toString().length;10>d;++d)b+="0";b+=e.low;k.href=w+b+"&rpe=1";l.href=h;k=KasperskyLab.GetPageWidth();h=n.getBoundingClientRect();e=h.width?h.width:h.right-h.left;h=h.height?h.height:h.bottom-h.top;l=e/2;m=l>m?0:l+m>k?k-e:m-l;e=KasperskyLab.GetPageHeight();f=f+h>e?f-h:f;0>f&&(f=0);h=KasperskyLab.GetPageScroll();f+=h.top;m+=h.left;n.style.position="absolute";n.style.top=
Math.round(f).toString()+"px";n.style.left=Math.round(m).toString()+"px";n.style.visibility="visible"}}})(KasperskyLab||{});
(function(c,y){function r(){try{s||(s=new u)}catch(c){y.Log("UrlAdvisor exception "+(c.message||c))}}var u=function(){function r(a){return 1E4>=(a>=z?a-z:0)?500:c.MaxRequestDelay}function s(a){y.Log("ERR UA - "+(a.message||a))}function v(a){try{return a.href}catch(c){}try{return a.getAttribute("href")}catch(b){}return""}function t(a){a=a.nextSibling;return null!==a&&"KavHltTag"===a.name}function n(a,c){var b=0;a.onmouseout=function(){b&&(window.clearTimeout(b),b=0)};a.onmouseover=function(a){b||(a=
a||event,b=window.setTimeout(function(a,b){return function(){q.ShowBalloon(a,b,c,C,D)}}(a.clientX,a.clientY),300))}}function m(a){for(var b=0;b<a.length;b++)for(var d=c.JSONParse(a[b]),e=0;e<document.links.length;e++){var g=document.links[e];if(d.url===v(g)&&(!u||c.IsLinkSearchResult(g))){if(!t(g)){var f=document.createElement("img");f.name="KavHltTag";f.width=12;f.height=12;g.parentNode.insertBefore(f,g.nextSibling)}var f=g=g.nextSibling,h=d;1===h.rating?(f.src=c.GetResourceSrc("/ua/UrlAdvisorGoodImage.png"),
f.kis_status=16):2===h.rating?(f.src=c.GetResourceSrc("/ua/UrlAdvisorSuspiciousImage.png"),f.kis_status=8):3===h.rating&&(f.src=c.GetResourceSrc("/ua/UrlAdvisorDangerImage.png"),f.kis_status=4);n(g,d)}}}function f(){for(var a=document.getElementsByName("KavHltTag");0<a.length;)a[0].parentNode.removeChild(a[0])}function e(a){f();0<a.length&&(p=(g="0"!=a[0])&&"Enabled"==A);p&&(u=!!(1<a.length&&1==a[1]),2<a.length&&(D=a[2]),3<a.length&&(C=a[3]));b()}function w(a){0<a.length&&(f(),A=a[0],p=g&&"Enabled"==
A,b())}function h(a){try{return!a.isContentEditable&&!!a.parentNode&&!t(a)&&(!u||c.IsLinkSearchResult(a))&&"balloon_external"!==a.id&&"balloon_terms"!==a.id}catch(b){return c.Log("IsNeedCategorizeLink exception: "+(b.message||b)),!1}}function k(a){if(1==a.nodeType&&"a"==a.nodeName.toLowerCase()&&t(a))a.parentNode.removeChild(a.nextSibling);else for(var b=0;b<a.childNodes.length;++b)k(a.childNodes[b])}function l(a){if(!B)if(1==a.nodeType&&"a"==a.nodeName.toLowerCase())setTimeout(b,500),B=!0;else for(var c=
0;c<a.childNodes.length;++c)l(a.childNodes[c])}function b(){if(p){B=!1;for(var a=[],b=0;b<document.links.length;b++){var d=document.links[b];if(h(d)){d.sended=!0;var e=v(d);e?a.push(e):c.Log('access to href "'+d.outerHTML+'" blocked by browser')}}a.length&&(E("ua.zaetcoiegr",a,null,s),z=c.GetCurrentTime())}}function d(){b();window.addEventListener("DOMNodeInserted",function(a){l(a.target)});window.addEventListener("DOMNodeRemoved",function(a){k(a.target)})}var q=new c.UrlAdvisorBalloon,
g=c.DefaultUrlAdvisorEnable,p=g&&"Enabled"==c.DefaultUrlAdvisorState,u=c.DefaultUrlAdvisorMode,C=c.DefaultUrlAdvisorInfoUrl,D=c.DefaultUrlAdvisorTermsUrl,B=!1,z=0,A=c.DefaultUrlAdvisorState,E;y.InitializePlugin(function(a,b,c){E=c;a("ua",r,s);b("ua.verdict",m);b("ua.settings",e);b("ua.state",w)});(function(){if("addEventListener"in window)d();else{b();var a=setInterval(function(){var a;a:{for(a=0;a<document.links.length;a++){var c=document.links[a];if(!c.sended&&h(c)){a=!0;break a}}a=!1}a&&b()},1E4);
c.AddEventListener(window,"unload",function(){clearInterval(a)})}})()},s=null;c.AddEventListener(window,"load",function(){r()});setTimeout(r,1E5)})(KasperskyLab||{},nssseaiesinontc);
(function(ns){ns.ConvertCategory=function(category){if (category === 1 )
return 'Adult content';
else if (category === 2 )
return 'Software, audio, video';
else if (category === 3 )
return 'Alcohol, tobacco, narcotics';
else if (category === 4 )
return 'Violence';
else if (category === 5 )
return 'Profanity, obscenity';
else if (category === 6 )
return 'Weapons, explosives, pyrotechnics';
else if (category === 7 )
return 'Gambling, lotteries, sweepstakes';
else if (category === 8 )
return 'Internet communication media';
else if (category === 9 )
return 'Internet communication media';
else if (category === 10 )
return 'Electronic commerce';
else if (category === 11 )
return 'Internet communication media';
else if (category === 12 )
return 'Job search';
else if (category === 13 )
return 'HTTP query redirection';
else if (category === 14 )
return 'Electronic commerce';
else if (category === 15 )
return 'Computer games';
else if (category === 16 )
return 'Payment systems';
else if (category === 17 )
return 'Bank websites';
else if (category === 18 )
return 'Discrimination';
else if (category === 19 )
return 'Dissatisfaction';
else if (category === 20 )
return 'Online stores with own payment systems';
else if (category === 21 )
return 'Police decision';
else if (category === 22 )
return 'Software, audio, video, and related content';
else if (category === 27 )
return 'Gambling, lotteries, and sweepstakes';
else if (category === 28 )
return 'Communication on Internet';
else if (category === 34 )
return 'Online business activities';
else if (category === 35 )
return 'Computer games';
else if (category === 36 )
return 'Religions';
else if (category === 37 )
return 'News media';
else return 'Unknown';};})(KasperskyLab || {});(function(ns){ns.IsLinkSearchResult=function(linkElement){return false;};})(KasperskyLab || {});
 })();

 })();
